-- MySQL Script generated by MySQL Workbench
-- 08/07/17 11:31:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fims
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fims
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fims` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fims` ;

-- -----------------------------------------------------
-- Table `fims`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `employee_lastname` VARCHAR(45) NULL COMMENT '',
  `employee_firstname` VARCHAR(45) NULL COMMENT '',
  `employee_number` INT NULL COMMENT '',
  `employee_email` VARCHAR(45) NULL COMMENT '',
  `employee_occupation` VARCHAR(45) NULL COMMENT '',
  `employee_user_type` VARCHAR(45) BINARY NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `schudule_date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`checklist` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `checklist_equipment` VARCHAR(45) NULL COMMENT '',
  `checklist_quantity_on_hand` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`facility` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `facility_type` VARCHAR(45) NULL COMMENT '',
  `facility_status` VARCHAR(45) NULL COMMENT '',
  `facility_qrcode` VARCHAR(45) NULL COMMENT '',
  `checklist_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `checklist_id`)  COMMENT '',
  INDEX `fk_facility_checklist1_idx` (`checklist_id` ASC)  COMMENT '',
  CONSTRAINT `fk_facility_checklist1`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `fims`.`checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`employee_has_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`employee_has_facility` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `employee_id` INT NULL COMMENT '',
  `facility_id` INT NULL COMMENT '',
  INDEX `fk_employee_has_facility_facility1_idx` (`facility_id` ASC)  COMMENT '',
  INDEX `fk_employee_has_facility_employee_idx` (`employee_id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_employee_has_facility_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `fims`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_facility_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `fims`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`employee_has_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`employee_has_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `employee_id` INT NULL COMMENT '',
  `schedule_id` INT NULL COMMENT '',
  INDEX `fk_employee_has_schedule_schedule1_idx` (`schedule_id` ASC)  COMMENT '',
  INDEX `fk_employee_has_schedule_employee1_idx` (`employee_id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_employee_has_schedule_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `fims`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_schedule_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `fims`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`schedule_has_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`schedule_has_facility` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `schedule_id` INT NULL COMMENT '',
  `facility_id` INT NULL COMMENT '',
  `facility_checklist_id` INT NULL COMMENT '',
  INDEX `fk_schedule_has_facility_facility1_idx` (`facility_id` ASC, `facility_checklist_id` ASC)  COMMENT '',
  INDEX `fk_schedule_has_facility_schedule1_idx` (`schedule_id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_schedule_has_facility_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `fims`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_has_facility_facility1`
    FOREIGN KEY (`facility_id` , `facility_checklist_id`)
    REFERENCES `fims`.`facility` (`id` , `checklist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
