-- MySQL Script generated by MySQL Workbench
-- 08/24/17 10:38:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fims
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fims
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fims` DEFAULT CHARACTER SET utf8 ;
USE `fims` ;

-- -----------------------------------------------------
-- Table `fims`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_lastname` VARCHAR(45) NULL,
  `employee_firstname` VARCHAR(45) NULL,
  `employee_number` INT NULL,
  `employee_occupation` VARCHAR(45) NULL,
  `employee_user_type` VARCHAR(45) BINARY NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schudule_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`checklist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checklist_equipment` VARCHAR(45) NULL,
  `checklist_quantity_on_hand` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `facility_type` VARCHAR(45) NULL,
  `facility_status` VARCHAR(45) NULL,
  `facility_qrcode` BINARY NULL,
  `checklist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `checklist_id`),
  INDEX `fk_facility_checklist1_idx` (`checklist_id` ASC),
  CONSTRAINT `fk_facility_checklist1`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `fims`.`checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`employee_has_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`employee_has_facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL,
  `facility_id` INT NULL,
  INDEX `fk_employee_has_facility_facility1_idx` (`facility_id` ASC),
  INDEX `fk_employee_has_facility_employee_idx` (`employee_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_has_facility_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `fims`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_facility_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `fims`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`employee_has_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`employee_has_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NULL,
  `schedule_id` INT NULL,
  INDEX `fk_employee_has_schedule_schedule1_idx` (`schedule_id` ASC),
  INDEX `fk_employee_has_schedule_employee1_idx` (`employee_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_has_schedule_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `fims`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_has_schedule_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `fims`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`schedule_has_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`schedule_has_facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schedule_id` INT NULL,
  `facility_id` INT NULL,
  `facility_checklist_id` INT NULL,
  INDEX `fk_schedule_has_facility_facility1_idx` (`facility_id` ASC, `facility_checklist_id` ASC),
  INDEX `fk_schedule_has_facility_schedule1_idx` (`schedule_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_schedule_has_facility_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `fims`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_has_facility_facility1`
    FOREIGN KEY (`facility_id` , `facility_checklist_id`)
    REFERENCES `fims`.`facility` (`id` , `checklist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fims`.`checklist_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fims`.`checklist_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checklist_template_type` VARCHAR(10) NULL,
  `checklist_template_equipment` VARCHAR(45) NULL,
  `checklist_template_temperature` DECIMAL(3,2) NULL,
  `checklist_template_equipment_number` INT NULL,
  `checklist_template_equipment_description` VARCHAR(60) NULL,
  `checklist_id` INT NOT NULL,
  PRIMARY KEY (`id`, `checklist_id`),
  INDEX `fk_checklist_template_checklist1_idx` (`checklist_id` ASC),
  CONSTRAINT `fk_checklist_template_checklist1`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `fims`.`checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
